/******************************************************************************
*  Generated by PSoC Designer 5.2.2401
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "CSD_1.h"

#endif
