/******************************************************************************
*  Generated by PSoC Designer 5.2.2401
******************************************************************************/
#include <m8c.h>
// CSD_1Capacitor address and mask defines
#pragma	ioport	CSD_1Capacitor_Data_ADDR:	0x0
BYTE			CSD_1Capacitor_Data_ADDR;
#pragma	ioport	CSD_1Capacitor_DriveMode_0_ADDR:	0x100
BYTE			CSD_1Capacitor_DriveMode_0_ADDR;
#pragma	ioport	CSD_1Capacitor_DriveMode_1_ADDR:	0x101
BYTE			CSD_1Capacitor_DriveMode_1_ADDR;
#pragma	ioport	CSD_1Capacitor_DriveMode_2_ADDR:	0x3
BYTE			CSD_1Capacitor_DriveMode_2_ADDR;
#pragma	ioport	CSD_1Capacitor_GlobalSelect_ADDR:	0x2
BYTE			CSD_1Capacitor_GlobalSelect_ADDR;
#pragma	ioport	CSD_1Capacitor_IntCtrl_0_ADDR:	0x102
BYTE			CSD_1Capacitor_IntCtrl_0_ADDR;
#pragma	ioport	CSD_1Capacitor_IntCtrl_1_ADDR:	0x103
BYTE			CSD_1Capacitor_IntCtrl_1_ADDR;
#pragma	ioport	CSD_1Capacitor_IntEn_ADDR:	0x1
BYTE			CSD_1Capacitor_IntEn_ADDR;
#define CSD_1Capacitor_MASK 0x8
#pragma	ioport	CSD_1Capacitor_MUXBusCtrl_ADDR:	0x1d8
BYTE			CSD_1Capacitor_MUXBusCtrl_ADDR;
// CSD_1SW0 address and mask defines
#pragma	ioport	CSD_1SW0_Data_ADDR:	0x4
BYTE			CSD_1SW0_Data_ADDR;
#pragma	ioport	CSD_1SW0_DriveMode_0_ADDR:	0x104
BYTE			CSD_1SW0_DriveMode_0_ADDR;
#pragma	ioport	CSD_1SW0_DriveMode_1_ADDR:	0x105
BYTE			CSD_1SW0_DriveMode_1_ADDR;
#pragma	ioport	CSD_1SW0_DriveMode_2_ADDR:	0x7
BYTE			CSD_1SW0_DriveMode_2_ADDR;
#pragma	ioport	CSD_1SW0_GlobalSelect_ADDR:	0x6
BYTE			CSD_1SW0_GlobalSelect_ADDR;
#pragma	ioport	CSD_1SW0_IntCtrl_0_ADDR:	0x106
BYTE			CSD_1SW0_IntCtrl_0_ADDR;
#pragma	ioport	CSD_1SW0_IntCtrl_1_ADDR:	0x107
BYTE			CSD_1SW0_IntCtrl_1_ADDR;
#pragma	ioport	CSD_1SW0_IntEn_ADDR:	0x5
BYTE			CSD_1SW0_IntEn_ADDR;
#define CSD_1SW0_MASK 0x10
#pragma	ioport	CSD_1SW0_MUXBusCtrl_ADDR:	0x1d9
BYTE			CSD_1SW0_MUXBusCtrl_ADDR;
// CSD_1SW0 Shadow defines
//   CSD_1SW0_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CSD_1SW0_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSD_1SW1 address and mask defines
#pragma	ioport	CSD_1SW1_Data_ADDR:	0x4
BYTE			CSD_1SW1_Data_ADDR;
#pragma	ioport	CSD_1SW1_DriveMode_0_ADDR:	0x104
BYTE			CSD_1SW1_DriveMode_0_ADDR;
#pragma	ioport	CSD_1SW1_DriveMode_1_ADDR:	0x105
BYTE			CSD_1SW1_DriveMode_1_ADDR;
#pragma	ioport	CSD_1SW1_DriveMode_2_ADDR:	0x7
BYTE			CSD_1SW1_DriveMode_2_ADDR;
#pragma	ioport	CSD_1SW1_GlobalSelect_ADDR:	0x6
BYTE			CSD_1SW1_GlobalSelect_ADDR;
#pragma	ioport	CSD_1SW1_IntCtrl_0_ADDR:	0x106
BYTE			CSD_1SW1_IntCtrl_0_ADDR;
#pragma	ioport	CSD_1SW1_IntCtrl_1_ADDR:	0x107
BYTE			CSD_1SW1_IntCtrl_1_ADDR;
#pragma	ioport	CSD_1SW1_IntEn_ADDR:	0x5
BYTE			CSD_1SW1_IntEn_ADDR;
#define CSD_1SW1_MASK 0x40
#pragma	ioport	CSD_1SW1_MUXBusCtrl_ADDR:	0x1d9
BYTE			CSD_1SW1_MUXBusCtrl_ADDR;
// CSD_1SW1 Shadow defines
//   CSD_1SW1_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define CSD_1SW1_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// CSD_1Resistor address and mask defines
#pragma	ioport	CSD_1Resistor_Data_ADDR:	0xc
BYTE			CSD_1Resistor_Data_ADDR;
#pragma	ioport	CSD_1Resistor_DriveMode_0_ADDR:	0x10c
BYTE			CSD_1Resistor_DriveMode_0_ADDR;
#pragma	ioport	CSD_1Resistor_DriveMode_1_ADDR:	0x10d
BYTE			CSD_1Resistor_DriveMode_1_ADDR;
#pragma	ioport	CSD_1Resistor_DriveMode_2_ADDR:	0xf
BYTE			CSD_1Resistor_DriveMode_2_ADDR;
#pragma	ioport	CSD_1Resistor_GlobalSelect_ADDR:	0xe
BYTE			CSD_1Resistor_GlobalSelect_ADDR;
#pragma	ioport	CSD_1Resistor_IntCtrl_0_ADDR:	0x10e
BYTE			CSD_1Resistor_IntCtrl_0_ADDR;
#pragma	ioport	CSD_1Resistor_IntCtrl_1_ADDR:	0x10f
BYTE			CSD_1Resistor_IntCtrl_1_ADDR;
#pragma	ioport	CSD_1Resistor_IntEn_ADDR:	0xd
BYTE			CSD_1Resistor_IntEn_ADDR;
#define CSD_1Resistor_MASK 0x2
#pragma	ioport	CSD_1Resistor_MUXBusCtrl_ADDR:	0x1db
BYTE			CSD_1Resistor_MUXBusCtrl_ADDR;
